Repository CS2103-AY1819S1-F10-4/main, pull requests merged in 2018-10, with the labels that each got.

#59 Update to version 1.2.0
  src/main/java/seedu/address/MainApp.java
Labels: status.review

#57 UserGuide: Corrected releases link and shorten command words
  docs/UserGuide.adoc
Labels: status.review

#67 DeveloperGuide: Reorder use cases from high to low priority
  docs/DeveloperGuide.adoc
Labels: status.review

#69 Side navigation bar
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/css/DarkTheme.css
  src/main/resources/css/Extensions.css
  src/main/resources/images/account.png
  src/main/resources/images/ingredient.png
  src/main/resources/images/menu.png
  src/main/resources/images/reservation.png
  src/main/resources/images/sales.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/default.html
  src/test/java/seedu/address/ui/testutil/UiPartRule.java
Labels: status.review

#73 Refactor command to create user accounts
  src/main/java/seedu/address/logic/commands/accounts/RegisterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/accounts/RegisterCommandParser.java
  src/test/java/seedu/address/logic/commands/accounts/RegisterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/accounts/RegisterCommandParserTest.java
  src/test/java/seedu/address/testutil/accounts/AccountUtil.java
Labels: status.review

#70 Hash password
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/accounts/Password.java
  src/test/java/seedu/address/logic/parser/accounts/RegisterCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/accounts/PasswordTest.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
Labels: status.review

#87 Remove force fix on UG
  docs/DeveloperGuide.adoc
Labels: status.review

#83 v1.2 Display Sales Report
  src/main/java/seedu/address/commons/events/ui/DisplaySalesReportEvent.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/sales/DisplaySalesCommand.java
  src/main/java/seedu/address/logic/commands/sales/RecordSalesCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/sales/DisplaySalesCommandParser.java
  src/main/java/seedu/address/logic/parser/sales/RecordSalesCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/salesrecord/Price.java
  src/main/java/seedu/address/model/salesrecord/QuantitySold.java
  src/main/java/seedu/address/model/salesrecord/SalesRecord.java
  src/main/java/seedu/address/model/salesrecord/SalesReport.java
  src/main/java/seedu/address/model/salesrecord/UniqueRecordList.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/sales/RecordCard.java
  src/main/java/seedu/address/ui/sales/SalesReportWindow.java
  src/main/resources/view/SalesReportWindow.fxml
  src/test/java/guitests/guihandles/sales/RecordCardHandle.java
  src/test/java/guitests/guihandles/sales/SalesReportWindowHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredients/AddIngredientCommandTest.java
  src/test/java/seedu/address/logic/commands/menu/AddItemCommandTest.java
  src/test/java/seedu/address/logic/commands/reservation/AddReservationCommandTest.java
  src/test/java/seedu/address/logic/commands/sales/DisplaySalesCommandTest.java
  src/test/java/seedu/address/logic/commands/sales/RecordSalesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/sales/DisplaySalesCommandParserTest.java
  src/test/java/seedu/address/logic/parser/sales/RecordSalesCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/salesrecord/SalesReportTest.java
  src/test/java/seedu/address/model/salesrecord/UniqueRecordListTest.java
  src/test/java/seedu/address/testutil/salesrecords/RecordUtil.java
  src/test/java/seedu/address/testutil/salesrecords/ReportBuilder.java
  src/test/java/seedu/address/ui/sales/RecordCardTest.java
  src/test/java/seedu/address/ui/sales/SalesReportWindowTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.review

#86 v1.2 Logging in and out
  src/main/java/seedu/address/commons/core/session/UserSession.java
  src/main/java/seedu/address/commons/events/ui/LoginEvent.java
  src/main/java/seedu/address/commons/events/ui/LogoutEvent.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/accounts/LoginCommand.java
  src/main/java/seedu/address/logic/commands/accounts/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/accounts/RegisterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/accounts/LoginCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/accounts/UniqueAccountList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/accounts/UsernameDisplay.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UsernameDisplay.fxml
  src/test/java/guitests/guihandles/UsernameHandle.java
  src/test/java/guitests/guihandles/accounts/UsernameDisplayHandle.java
  src/test/java/seedu/address/commons/core/session/UserSessionTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/accounts/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/accounts/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/accounts/RegisterCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredients/AddIngredientCommandTest.java
  src/test/java/seedu/address/logic/commands/menu/AddItemCommandTest.java
  src/test/java/seedu/address/logic/commands/reservation/AddReservationCommandTest.java
  src/test/java/seedu/address/logic/commands/sales/RecordSalesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/accounts/LoginCommandParserTest.java
  src/test/java/seedu/address/model/accounts/UniqueAccountListTest.java
  src/test/java/seedu/address/testutil/accounts/AccountUtil.java
  src/test/java/seedu/address/ui/accounts/UsernameDisplayTest.java
Labels: status.review

#92 v1.2 Delete & Edit sales record by index
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/sales/DeleteSalesCommand.java
  src/main/java/seedu/address/logic/commands/sales/DisplaySalesCommand.java
  src/main/java/seedu/address/logic/commands/sales/EditSalesCommand.java
  src/main/java/seedu/address/logic/commands/sales/RecordSalesCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/sales/DeleteSalesCommandParser.java
  src/main/java/seedu/address/logic/parser/sales/EditSalesCommandParser.java
  src/main/java/seedu/address/model/salesrecord/ItemNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/sales/RecordCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/sales/DeleteSalesCommandTest.java
  src/test/java/seedu/address/logic/commands/sales/EditRecordDescriptorTest.java
  src/test/java/seedu/address/logic/commands/sales/EditSalesCommandTest.java
  src/test/java/seedu/address/logic/commands/sales/RecordSalesCommandIntegrationTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/sales/DeleteSalesCommandParserTest.java
  src/test/java/seedu/address/logic/parser/sales/EditSalesCommandParserTest.java
  src/test/java/seedu/address/model/salesrecord/ItemNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/salesrecords/EditRecordDescriptorBuilder.java
  src/test/java/seedu/address/testutil/salesrecords/RecordUtil.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.review

#91 v1.2: Feature/ingredient management
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/DisplayIngredientListRequestEvent.java
  src/main/java/seedu/address/logic/commands/ingredients/AddIngredientCommand.java
  src/main/java/seedu/address/logic/commands/ingredients/DeleteIngredientByIndexCommand.java
  src/main/java/seedu/address/logic/commands/ingredients/DeleteIngredientByNameCommand.java
  src/main/java/seedu/address/logic/commands/ingredients/DeleteIngredientCommand.java
  src/main/java/seedu/address/logic/commands/ingredients/EditIngredientCommand.java
  src/main/java/seedu/address/logic/commands/ingredients/ListIngredientsCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ingredients/DeleteIngredientCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ingredient/Ingredient.java
  src/main/java/seedu/address/model/ingredient/UniqueIngredientList.java
  src/main/java/seedu/address/ui/IngredientListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredients/AddIngredientCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredients/DeleteIngredientByIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredients/DeleteIngredientByNameCommandTest.java
  src/test/java/seedu/address/logic/commands/menu/AddItemCommandTest.java
  src/test/java/seedu/address/logic/commands/reservation/AddReservationCommandTest.java
  src/test/java/seedu/address/logic/commands/sales/RecordSalesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ingredients/DeleteIngredientCommandParserTest.java
  src/test/java/seedu/address/model/ingredient/IngredientTest.java
Labels: status.review

#103 v1.2: Certain commands can only be executed when authenticated
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/LoginEvent.java
  src/main/java/seedu/address/commons/events/ui/LogoutEvent.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/accounts/LoginCommand.java
  src/main/java/seedu/address/logic/commands/accounts/LogoutCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: status.review

#100 Edit and remove reservation
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/reservation/DeleteReservationCommand.java
  src/main/java/seedu/address/logic/commands/reservation/EditReservationCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/reservation/DeleteReservationCommandParser.java
  src/main/java/seedu/address/logic/parser/reservation/EditReservationCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/reservation/DeleteReservationCommandTest.java
  src/test/java/seedu/address/logic/commands/reservation/EditReservationCommandTest.java
  src/test/java/seedu/address/logic/commands/reservation/ReservationCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/reservation/DeleteReservationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/reservation/EditReservationCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/reservation/EditReservationDescriptorBuilder.java
  src/test/java/seedu/address/testutil/reservation/TypicalReservations.java
Labels: status.review

#97 v1.2: Update to UG and DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: status.review

#115 Configure RepoSense
  .gitignore
  _reposense/config.json
Labels: status.review

#116 v1.2: Update UGDG for Ingredient Management
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/DeleteIngByIndexSequenceDiagram.png
  docs/images/DeleteIngByNameSequenceDiagram.png
Labels: component.docs, status.review

#114 v1.2 Update UGDG with menu features
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: component.docs, status.review

#118 v1.2: Update UGDG Ingredient Management
  docs/DeveloperGuide.adoc
  docs/images/DeleteIngredientByIndexSequenceDiagram.png
  docs/images/DeleteIngredientByNameSequenceDiagram.png
Labels: component.docs, status.ongoing

#119 v1.2 Update UGDG sales management
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: component.docs, status.review

#120 Update User Guide: General
  docs/UserGuide.adoc
Labels: component.docs, status.review

#117 v1.2: Update to UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/RegisterSequenceDiagram.pptx
  docs/diagrams/UserSessionActivityDiagram.pptx
  docs/images/RegisterSequenceDiagram.png
  docs/images/UserSessionActivityDiagram.png
Labels: component.docs, status.review

#121 v1.3: Update app version
  src/main/java/seedu/address/MainApp.java
Labels: status.review

#122 v1.3: Delete account
  src/main/java/seedu/address/logic/commands/accounts/DeregisterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/accounts/DeregisterCommandParser.java
  src/main/java/seedu/address/model/accounts/Account.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/accounts/DeregisterCommandTest.java
  src/test/java/seedu/address/logic/commands/accounts/RegisterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/accounts/DeregisterCommandParserTest.java
  src/test/java/seedu/address/model/accounts/AccountTest.java
Labels: status.review

#131 README: Remove SE-education line
  README.adoc
Labels: component.docs, status.review

#133 v1.3: Set to default data rather than blank XML
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
Labels: component.model, component.storage, priority.high, status.review

#134 v1.3: Remove redundant log from UserSession
  src/main/java/seedu/address/commons/core/session/UserSession.java
  src/main/java/seedu/address/logic/commands/accounts/LoginCommand.java
  src/test/java/seedu/address/commons/core/session/UserSessionTest.java
Labels: component.logic, component.storage, status.review

#141 Add sequence diagram for section 4.4.1 of DG
  docs/DeveloperGuide.adoc
  docs/diagrams/DisplaySalesSequenceDiagram.pptx
  docs/images/DisplaySalesSequenceDiagram.png
Labels: component.docs, status.review

#135 v1.3: Mask password
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/accounts/DeregisterCommand.java
  src/main/java/seedu/address/logic/commands/accounts/LoginCommand.java
  src/main/java/seedu/address/logic/commands/accounts/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/accounts/RegisterCommand.java
  src/main/java/seedu/address/model/accounts/Password.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/commands/accounts/LoginCommandTest.java
Labels: component.logic, status.review

#145 Remove stray file
  src/test/data/sandboxmanyPersons.xml
Labels: status.review

#139 v1.3: Various Reservation Commands
  src/main/java/seedu/address/commons/events/ui/reservation/DisplayReservationListRequestEvent.java
  src/main/java/seedu/address/logic/commands/reservation/ListReservationsCommand.java
  src/main/java/seedu/address/logic/commands/reservation/SelectReservationCommand.java
  src/main/java/seedu/address/logic/commands/reservation/SortReservationsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/reservation/SelectReservationCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/reservation/UniqueReservationList.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/reservation/ReservationListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredients/AddIngredientCommandTest.java
  src/test/java/seedu/address/logic/commands/menu/AddItemCommandTest.java
  src/test/java/seedu/address/logic/commands/reservation/AddReservationCommandTest.java
  src/test/java/seedu/address/logic/commands/reservation/ListReservationsCommandTest.java
  src/test/java/seedu/address/logic/commands/reservation/SelectReservationCommandTest.java
  src/test/java/seedu/address/logic/commands/reservation/SortReservationsCommandTest.java
  src/test/java/seedu/address/logic/commands/sales/RecordSalesCommandTest.java
  src/test/java/seedu/address/logic/parser/reservation/SelectReservationCommandParserTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
Labels: component.logic, component.model, component.ui, priority.high, status.review

#148 v1.3 mass discount items
  src/main/java/seedu/address/logic/commands/menu/DiscountItemCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/menu/DiscountItemCommandParser.java
  src/test/java/seedu/address/logic/commands/menu/DiscountItemCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/menu/DiscountItemCommandParserTest.java
Labels: component.logic, status.review

#155 v1.3: Add alias for `help`, `exit` and `history`
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/accounts/AccountUtil.java
Labels: component.logic, status.review

#162 v1.3: Update parser test to improve coverage
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/reservation/ReservationUtil.java
Labels: component.logic, status.review

#179 Integration/stockup consume interfaces
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ingredient/UniqueIngredientList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredients/AddIngredientCommandTest.java
  src/test/java/seedu/address/logic/commands/menu/AddItemCommandTest.java
  src/test/java/seedu/address/logic/commands/reservation/AddReservationCommandTest.java
  src/test/java/seedu/address/logic/commands/sales/RecordSalesCommandTest.java
  src/test/java/seedu/address/model/ingredient/UniqueIngredientListTest.java
Labels: component.model, status.review

#180 v1.3: Update model class diagrams in DG
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagramNew.png
Labels: component.docs, status.review

#182 v1.3: ParserUtil: Refactor accounts related into its own util class
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/accounts/AccountParserUtil.java
  src/main/java/seedu/address/logic/parser/accounts/ChangePasswordCommandParser.java
  src/main/java/seedu/address/logic/parser/accounts/DeregisterCommandParser.java
  src/main/java/seedu/address/logic/parser/accounts/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/accounts/RegisterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/IngredientListCard.fxml
  src/main/resources/view/IngredientListPanel.fxml
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/ItemListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/RecordListCard.fxml
  src/main/resources/view/RecordListPanel.fxml
  src/main/resources/view/ReservationListCard.fxml
  src/main/resources/view/ReservationListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/SalesReportWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/guitests/guihandles/sales/RecordCardHandle.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/accounts/AccountParserUtilTest.java
  src/test/java/seedu/address/logic/parser/sales/RecordSalesCommandParserTest.java
  src/test/resources/view/UiPartTest/validFileWithFxRoot.fxml
Labels: status.review

#181 v1.3: Command/low stock
  src/main/java/seedu/address/logic/commands/ingredients/LowStockCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ingredient/MinimumUnit.java
  src/main/java/seedu/address/storage/elements/XmlAdaptedIngredient.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ingredients/LowStockCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ingredient/MinimumUnitTest.java
  src/test/java/seedu/address/testutil/ingredients/EditIngredientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ingredients/IngredientBuilder.java
  src/test/java/seedu/address/testutil/ingredients/TypicalIngredients.java
Labels: component.logic, component.model, status.review

#184 v1.3: Add one-liner to README & UG
  README.adoc
  docs/UserGuide.adoc
Labels: component.docs, status.review

#183 v1.3: Sales panel and Auto-ingredients update
  docs/diagrams/DisplaySalesSequenceDiagram.pptx
  docs/images/DisplaySalesSequenceDiagram.png
  src/main/java/seedu/address/commons/events/ui/DisplayRecordListRequestEvent.java
  src/main/java/seedu/address/logic/commands/sales/DeleteSalesCommand.java
  src/main/java/seedu/address/logic/commands/sales/EditSalesCommand.java
  src/main/java/seedu/address/logic/commands/sales/RecordSalesCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/reservation/Reservation.java
  src/main/java/seedu/address/model/salesrecord/Date.java
  src/main/java/seedu/address/model/salesrecord/SalesRecord.java
  src/main/java/seedu/address/model/salesrecord/exceptions/RequiredIngredientsNotFoundException.java
  src/main/java/seedu/address/storage/elements/XmlAdaptedRecord.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/sales/RecordCard.java
  src/main/java/seedu/address/ui/sales/RecordStackPanel.java
  src/main/java/seedu/address/ui/sales/SalesReportWindow.java
  src/main/resources/css/DarkTheme.css
  src/main/resources/view/RecordStackPanel.fxml
  src/test/data/XmlSerializableAddressBookTest/duplicateRecordAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalAddressBook.xml
  src/test/java/guitests/guihandles/sales/RecordStackPanelHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredients/AddIngredientCommandTest.java
  src/test/java/seedu/address/logic/commands/sales/RecordSalesCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/sales/RecordSalesCommandTest.java
  src/test/java/seedu/address/model/ingredient/UniqueIngredientListTest.java
  src/test/java/seedu/address/model/salesrecord/DateTest.java
  src/test/java/seedu/address/storage/salesrecords/XmlAdaptedRecordTest.java
  src/test/java/seedu/address/testutil/salesrecords/RecordBuilder.java
  src/test/java/seedu/address/ui/sales/RecordStackPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: component.logic, component.storage, component.ui, status.review

#188 Bug: menu stack panel
  src/main/java/seedu/address/logic/commands/menu/AddRequiredIngredientsCommand.java
  src/main/java/seedu/address/logic/commands/menu/RecipeItemCommand.java
  src/main/java/seedu/address/ui/menu/ItemStackPanel.java
  src/test/java/seedu/address/ui/menu/ItemStackPanelTest.java
Labels: status.review, type.bug
